### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by daibatzu** [joaoventura/pylibui#58]
Really sorry for being a noob here but I keep getting an error when trying to run a pylibui sample application. I set it up by doing the following on my Windows 10 64-bit machine.

1. Downloaded pylibui from github, unzipped and run python setup.py install
2. This now creates the pylibui package in C:\Python35\Lib\site-packages\pylibui
3. I now create a folder called sharedlibs in C:\Python35\Lib\site-packages\pylibui\libui
4. I copy the results of my cmake into this folder. the files are as follows:
 libui.dll, libui.pdb, libui.lib, cpp-multithread.pdb, cpp-multithread.exe, controlgallery.exe, controlgallery.pdb, histogram.exe, histogram.pdb, test.exe, test.pdb

However, my programs fail to run and I get the following error:

c:\Apps\Python>python libuitest.py
Traceback (most recent call last):
  File "libuitest.py", line 1, in <module>
    from pylibui.core import App
  File "C:\Python35\lib\site-packages\pylibui\core.py", line 6, in <module>
    from . import libui
  File "C:\Python35\lib\site-packages\pylibui\libui\__init__.py", line 24, in <module>
    ctypes.cdll.LoadLibrary(SHARED_LIBS)
  File "C:\Python35\lib\ctypes\__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python35\lib\ctypes\__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Any help?

**Comment by daibatzu** [comment]
Fixed this by modifying _init_.py. It seems that there were some required dll's that weren't loading. 
I now have:

SHARED_LIBS = "C:\Windows\System32\libui.dll"

I also moved msvcp120.dll and msvcr120.dll to C:\Windows\System32. 
Works now on windows 10 64 bit
