### ISSUE TITLE
controls folder not getting copied when installing via setup.py

### ISSUE THREAD

**Issue by rangeli** [joaoventura/pylibui#61]
Followed your guide in the README and did the following:

```bash
sudo -H python3 setup.py install
```

When trying to run the example on the README, I would get this error:

```bash
Traceback (most recent call last):
  File "pylibui-test.py", line 1, in <module>
    from pylibui.core import App
  File "/usr/local/lib/python3.5/dist-packages/pylibui/core.py", line 6, in <module>
    from . import libui
  File "/usr/local/lib/python3.5/dist-packages/pylibui/libui/__init__.py", line 24, in <module>
    ctypes.cdll.LoadLibrary(SHARED_LIBS)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/python3.5/dist-packages/pylibui/libui/sharedlibs/libui.so: cannot open shared object file: No such file or directory
```
Fixed this by copying over the `sharedlibs/` folder but then I got this error:

```bash
Traceback (most recent call last):
  File "pylibui-test.py", line 2, in <module>
    from pylibui.controls import Window
ImportError: No module named 'pylibui.controls'
```

This had me stumped until I realized that the entire `controls/` folder was not copied during setup.  Once I manually copied it over to the install location, then it worked fine.

If you can, please change your setup procedure to automatically take care of these steps to make installation of this library painless.

**Comment by waghanza** [comment]
#63

**Comment by waghanza** [comment]
@rangeli I have merged a fixed into **master**, so I close the issue ;-)
