### ISSUE TITLE
Issue building: AttributeError: /usr/lib/x86_64-linux-gnu/libui.so.1: undefined symbol: uiInit

### ISSUE THREAD

**Issue by bjd2385** [joaoventura/pylibui#74]
I keep getting the following error after building. Any recommendations on how I can fix this?

```Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pylibui.core import App
>>> app = App()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/brandon/anaconda3/lib/python3.6/site-packages/pylibui-0.0.1-py3.6.egg/pylibui/core.py", line 17, in __init__
    libui.uiInit(options)
  File "/home/brandon/anaconda3/lib/python3.6/site-packages/pylibui-0.0.1-py3.6.egg/pylibui/libui/main.py", line 24, in uiInit
    return clibui.uiInit(ctypes.byref(options))
  File "/home/brandon/anaconda3/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/home/brandon/anaconda3/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libui.so.1: undefined symbol: uiInit```

I've followed the instructions on building `libui` and `pylibui` in the `README`.

**Comment by bauripalash** [comment]
I got same problem
